apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-server-sso
  namespace: workflows
spec:
  encryptedData:
    client-secret: AgAaIvfZseCgeV67bgEhej5kcAyGVQkULhLHq3PBGgId9Gdb7tRaB9vtIRChlysbROxYKaQ845MMrQIpOcpbjHUhv5wspFBLK2F7JWfSpjf8R04IYq0+HmMa5cjxKHYX/vynSa9gd9uG3ote/a3Gw37DJqA+i1YGIiQinM03fpc783/mo6J8+QlwC3L4ss6a8M6NwpBM2MsapnWRP6Wu+y1heTJwrQLBOKkQnibO9vmXRjkMO7FyJvUlMNyKrRrOtCcJjN8GrK0JdTpnmOO0TsD6XV++plYs+6BMCLJxnGa0Xw6TDelrN+OpuIzCWZ8nDblTT+AtiNZ43yKkyZ7dCezVcYe3OtJXRWNfXf2ipamy/TTFrm843Cnq23xJLYhqehyVqKXFrO6n4u/Xv6V8IIogNC4H7fYMQXxMVOS2ITwk7Zibjm6rC3y3jv3d6kLcCwjUcr7xIEqx6NwiJK6DbKtj3j+ZMY4npyjUiRbTMJ4E2xDNM8jxsuOgArIN5RtGk6eQ6pqPv39LxkMrY8FGbFAqrxRLhzIV9dWSkQ0QUB+WPBlt8VGahtKbbc1axSF3kgz/HPg7SCFgzaNuowbS/BpZxAGYf+as8REz0wF+zCLy1e9Xh5IOTWxlNwBqicOS1J3NWRqO6kvi/ZiV46sQNHxXmNPb+TNHVtj3Sn1/lxDlI6eH+qG2dAfR9w3UltW/8TcQC0YwzXB2fS0iZDBOfj4Vci3Hybgpekspb88gomuKFw==
  template:
    metadata:
      name: argo-server-sso
      namespace: workflows

